/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'James Nugent' at '1/22/15 5:40 PM' with Gradle 2.2.1
 *
 * @author James Nugent, @date 1/22/15 5:40 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
